### ISSUE TITLE
Infinite loop with Absurdity Unleashed and Sneaky-Beaky

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#100]
Version 0.22.2 on Linux.
The Concentration card Absurdity Unleashed Interprets a Torment for 4 whenever Confuse is applied. The Concentration card Sneaky-Beaky applies Confuse when a Torment is Interpreted. When these two cards are both active it starts an infinite loop ending when the Torment perishes. The Sneaky Beaky must truly unleash the absurd!

**Comment by db0** [comment]
Hah, good catch. Hilariously thematic, but OP AF :D
