### ISSUE TITLE
Overwhelming Presence card does not play nicely with Courage

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#102]
The Action card Overwhelming Presence Interprets Torments for (Concentration * 6). If the dreamer has Concentration carried over as a result of Courage (Concentration is not lost at end of turn), that Concentration is not taken into account by Overwhelming Presence.

**Comment by db0** [comment]
Are you sure? It seems to be working fine for me

**Comment by simply-peachy** [comment]
Yes but the screenshot I took seems to have failed to grab what I wanted it to. I'll try to re-create and let you know.

**Comment by db0** [comment]
OK, because I cannot replicate it

**Comment by db0** [comment]
As there has been no replication until now, I'm closing this
