### ISSUE TITLE
Game force unstuck during Ordeal with The Laughing Ones

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#111]
This bug's still having a laugh with version 0.22.6. The unsticking worked nicely.
![Screenshot_20211230_230614](https://user-images.githubusercontent.com/51796618/147793480-0189bf1d-e2e0-4893-81e4-c9976e53a441.png)
[godot.log](https://github.com/db0/hypnagonia/files/7794857/godot.log)

**Comment by simply-peachy** [comment]
Happened soon after but with more juicy details in the log.
[godot_2.log](https://github.com/db0/hypnagonia/files/7794861/godot_2.log)

**Comment by db0** [comment]
Hm, No grudge this time, but looks like it was caused by Doubt? Grrr.

**Comment by simply-peachy** [comment]
v0.22.4. They're still laughing. I'm starting too, as well :-P
[godot.log](https://github.com/db0/hypnagonia/files/7799910/godot.log)

**Comment by simply-peachy** [comment]
v0.24.7. Lots of Grudge flying around.
[godot.log](https://github.com/db0/hypnagonia/files/7802718/godot.log)
![Screenshot_20220103_153356](https://user-images.githubusercontent.com/51796618/147949357-0aa23a3b-9d8b-487a-999e-ae63b85cf2f8.png)

**Comment by simply-peachy** [comment]
Another with v0.24.7.
Played Clown, then next turn Utterly Ridiculous then Fowl Language, so lots of debuffs flying around. They weren't laughing much after that. Three perished and one was left.
[laughing_doubt.log](https://github.com/db0/hypnagonia/files/7803422/laughing_doubt.log)
![Screenshot_20220103_182724](https://user-images.githubusercontent.com/51796618/147965991-6ae928ff-6932-45bb-bc3d-0f880ffb9158.png)

**Comment by simply-peachy** [comment]
Another one from v0.27.3 I'm afraid.
[more-stuck-lolers_godot.log](https://github.com/db0/hypnagonia/files/7826182/more-stuck-lolers_godot.log)

**Comment by db0** [comment]
I'm trying to piece what happened here. The laughing one did not exist at the start of your turn, right? So it spawned during the Bully's turn, then immediately died?

**Comment by simply-peachy** [comment]
I can't remember and didn't think to make a note. I will do next time.

**Comment by db0** [comment]
I added some extra debug code which will hopefully help me if/when this happens again

**Comment by simply-peachy** [comment]
v0.29.2. Previous turn had two lolers. I overcame them both via direct Interpretation cards and they both disappeared, but did have Rubber Eggs' effect active. On the Torments' next turn the Bully summoned a new loler and the game stuck.
[lolers_v0.29.2_godot.log](https://github.com/db0/hypnagonia/files/7834277/lolers_v0.29.2_godot.log)
![Screenshot_20220109_005204](https://user-images.githubusercontent.com/51796618/148664904-5f282e74-dda3-4312-b2d0-c9816d833aa4.png)

**Comment by simply-peachy** [comment]
Hi, remember me? Remember my friends that you hate so? They're back in v0.35.1! In the previous turn I had some Untouchable stacks which made the asskicking I got slightly less painful, then had the warning banner appear.

[godot.log](https://github.com/db0/hypnagonia/files/8240395/godot.log)
![Screenshot_20220313_184917](https://user-images.githubusercontent.com/51796618/158074606-f053a777-cb4f-4721-a925-1a69ea370789.png)
