### ISSUE TITLE
Crash when recalling the Playground Memory

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#113]
v0.22.6. 
The first card it played was a Confidence with Release, not sure of the second as then the crash occurred.
[godot.log](https://github.com/db0/hypnagonia/files/7794909/godot.log)

**Comment by db0** [comment]
Is that the same ordeal which was force-unstuck?

**Comment by simply-peachy** [comment]
It was a later Ordeal in the same game and didn't feature The Laughing Ones.
