### ISSUE TITLE
Buff from Concentration card Lash-out does not work

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#116]
v0.22.6. The Concentration card Lash-out applies buff: "After you take Anxiety, Interpret a random Torment for the same amount". During two Ordeals I had played this card and the buff icon was showing on dreamer. No retaliatory Interpretation was applied.

**Comment by db0** [comment]
Was it interpretation during your turn, or stress from the Torments?

**Comment by simply-peachy** [comment]
I am fairly sure it was Stress applied by the Torments. Neither had Concentration or any other buff that would have caused them to take no Interpretation.

**Comment by db0** [comment]
Then it's working as intended. Lash-out only mirrors damage you take during your own turn ;) (Otherwise it would be pretty broken)

**Comment by simply-peachy** [comment]
Gah, once again I only read half the card. Does the hover-over for the buff state this, too?

**Comment by db0** [comment]
should do. It's the exact same text as the card ;)
