### ISSUE TITLE
Should autoplaying X-cost cards use immersion?

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#117]
The Memory "Playground" plays the top two cards of the deck. I recalled the Memory and one of the cards it played was an 8X Confrontation. This applied 8X my 3 Immersion to an Ordeal, but didn't reduce my Immersion.

**Comment by db0** [comment]
At the moment this is working as intended. Autoplaying cards like that doesn't cost energy. Do you think X cards should be an exception?

**Comment by simply-peachy** [comment]
Hmm good question. X cards are meant to be very powerful under the right conditions, but it felt odd that I got to use all that power without having to give up playing any more cards.

**Comment by db0** [comment]
OK, we can re-open this if we feel it's too unbalanced
