### ISSUE TITLE
Memory "Playground" causes crash when playing "Safety of Air"

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#118]
v0.22.6. I had 0 Anxiety at the time, because I thought I was going to win this time. Playing Safety of Air myself didn't crash with 0 Anxiety, as I had done this in the previous turn.
[godot.log](https://github.com/db0/hypnagonia/files/7795965/godot.log)

**Comment by db0** [comment]
Hmm, I can't replicate this. Was this during the unstuck ordeal?

**Comment by simply-peachy** [comment]
No, but I did have to unstick during this game.

**Comment by db0** [comment]
I think I may have fixed this with another patch. Lemme know if it happens again
