### ISSUE TITLE
Risky Dream 3 "Gain a random Understanding card" choice gives no card

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#135]
v0.24.0. The max Anxiety was decreased but the card wasn't added to my library. I demand to see the manager!
![Screenshot_20220102_072935](https://user-images.githubusercontent.com/51796618/147869642-c15a6d70-fa40-441c-8048-fb6b7f448e9e.png)
[godot.log](https://github.com/db0/hypnagonia/files/7798797/godot.log)

**Comment by db0** [comment]
Huh, strange. I know I've tested this

**Comment by db0** [comment]
This is weird. It's working fine in debug. Lemme try with the export

**Comment by db0** [comment]
Can't replicate this, but added some debug prints. Let me know if it happens again.

**Comment by db0** [comment]
As there has been no replication until now, I'm closing this
