### ISSUE TITLE
Cannot upgrade Memory

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#136]
v0.22.4
I have enough released loneliness to upgrade this Memory but clicking on it does nothing. If I recall correctly, the game does allow to purchase a Memory and upgrade another in one session?
![Screenshot_20220102_075812](https://user-images.githubusercontent.com/51796618/147869707-76fa1d61-7663-4366-b68e-09f3af35d334.png)
![Screenshot_20220102_075902](https://user-images.githubusercontent.com/51796618/147869709-3130f98a-2474-42c0-b0bf-02b98fc4ab68.png)

**Comment by db0** [comment]
Yes it should allow it. Weird. I'll check
