### ISSUE TITLE
Cannot steal Clarity buff, but Hyena card still reduces stacks

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#146]
v0.24.4. When casting the Understanding card Hyena on the Indescribable Absurdity, its Clarity buff is reduced but is not added to the Dreamer. This behaviour might be by design (Clarity applies Stress), thought I'd report anyway.
In the screenshot the Clarity was reduced from 3 to 1 but didn't apply to the Dreamer.
[hyena_godot.log](https://github.com/db0/hypnagonia/files/7802973/hyena_godot.log)

![absurdity_steal_clarity](https://user-images.githubusercontent.com/51796618/147955361-a073c453-af81-42d4-8d5c-646578a7c49c.png)

**Comment by db0** [comment]
That is actually working as intended. Clarity counters Confusion and you'll notice you have confusion stacks. Those were probably higher before you played the card. So instead of giving you both effects, it simply reduced your stack of confusion by the same amount ;)
