### ISSUE TITLE
Nice Warm Meal Curio didn't proc

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#148]
I received the Nice Warm Meal Curio a fair few events ago and may have since upgraded the affected card. No sign of a card with zero Immersion, that usually costs 1+. Note I upgraded many cards to their free variants.  I don't recall seeing a green Immersion value at all.

[nice_warm_meal.log](https://github.com/db0/hypnagonia/files/7803511/nice_warm_meal.log)
![Screenshot_20220103_183553](https://user-images.githubusercontent.com/51796618/147967329-6636f8e1-39e3-4765-b898-2fa18f69ef36.png)
![Screenshot_20220103_183546](https://user-images.githubusercontent.com/51796618/147967333-bc849811-7637-4f50-835e-23afab8f975f.png)
![Screenshot_20220103_183528](https://user-images.githubusercontent.com/51796618/147967334-b8b2391c-8bc8-4ebc-bd92-8288932fa0e3.png)
![Screenshot_20220103_183522](https://user-images.githubusercontent.com/51796618/147967336-70aeebf8-431f-4692-89c0-563359cdada2.png)

**Comment by db0** [comment]
Note that it doesn't paint the immersion cost green in the deck. I'm going to add functionality later.
