### ISSUE TITLE
Notes on winning and losing, for balancing

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#149]
Since the recent balancing:
I've won twice.

1. 	Easy win. vs Surreality. I had loads of Concentration, started with very low Anxiety, stacked loads of Grudge.
2. 	Challenging win vs. Surreality. I started at 42/100 Anxiety, won at 97/100! I kept a mid-range but consistent Doubt on it, had quite a few higher direct Interpret cards and strong Concentrate/Untouchable.

I've lost six times

1. 	Narcissus. A fair loss - didn't have enough Concentration / Stress avoidance
2. 	Narcissus. A fair loss - started Ordeal with >50 Anxiety. Some of the heavy Stress got through, some hits from Gaslighter, Doubt needled at the remainder.
3. 	Narcissus. Challenging. Doubt did a lot of cumulative damage, started with ~40/95 Anxiety and wasn't Stressed by all that much. Just couldn't hit it hard enough, it won with 140/200 HP.
4. 	Absurdity, second appearance. Started 89/100 Anxiety as a result of Risky Dream 3 (I took one option and then the exit). Le ded.
5. 	Narcissus. Epic battle. I had Concentration stacked to 35, constant low-level Grudge against it. It was 198 for 200, I was 4 from waking up...but had 5 Doubt on me. Ended turn, Narcissus hit me for 1 Stress, died, I took Doubt, died. NICE.
6. 	Narcissus. I was thrashed. Started with 30/40 of 95 Anxiety, took a lot of Stress and fair bit of Doubt. Managed to scrape through the last five turns, watching the Doubt slowly grind away. It was left for 106/200HP and had a 0/28 Gaslighter left.

**Comment by db0** [comment]
Thanks. As discussed I'm closing this issue as there's nothing specific to fix. I'll continue working on the balance as always
