### ISSUE TITLE
Save/Load functionality

### ISSUE THREAD

**Issue by db0** [db0/hypnagonia#152]

**Comment by SkylarkHYP** [comment]
This is CRITIICALLY needed. 
I would suggest a import/export generated code that players can copy and paste,
or a login system through username/password/email.

I'm having trouble playing 4 hour runs, as well as losing all my progress if something interrupts the web/executable. So I would greatly appreciate if this was added.

**Comment by db0** [comment]
Fair enough. I'll see if I can add an interim solution

**Comment by SkylarkHYP** [comment]
Thank you so much! :)

> Fair enough. I'll see if I can add an interim solution
