### ISSUE TITLE
Dragging Action card to target with "Enough is Enough" is bugged

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#161]
The choice selection prompt for Enough is Enough ought to trigger once the card has been dragged to its target. Currently when starting to drag the card the prompt shows but with the card "stuck" to the cursor. You have to then click on the prompt, which closes but ignores the choice, click to drop the card, then the prompt opens again. Can then make a choice and click on target.

Double-clicking the card works OK.

**Comment by db0** [comment]
Oh yeah, this is happening because I now display results also on cards which do not have targets, while dragging them. I'll fix
