### ISSUE TITLE
Build the Boss Shop

### ISSUE THREAD

**Issue by db0** [db0/hypnagonia#185]
There should be a shop that sells stuff using released closure only.

**Comment by SkylarkHYP** [comment]
- [ ]  **The subconscious marketplace**

 was just around the corner! Figments from all walks of life welcomed me with open arms. I could smell the aroma of delicious pastries, and I could hear the obsessive haggling of exotic thoughts before me. Was that a familiar face I see?

The subconscious marketplace has a 1*repressed closure% chance to appear as a choice in the dream journal after **fully overcoming** an elite torment. And has a 100% chance to appear in the beginning of the next act after fully overcoming a boss torment. 
- [ ] The grand marketplace will be disabled when you disable deep torpor.

Will give you three choices that rerolls choices upon buying one, each - [ ] cost 10 released closure, 
- [ ] the player has a 5% chance to gain e perturbation instead upon buying a choice, if you happen to get a perturbation you are booted out of there! (Infestation is more likely to be a perturbation here)

 
 Choices include: 
 1-5 enhancements to a random card (shows which one) 15%
Rare curios  5%
relax for 10-30 anxiety (aka. Song) 10%
Rare cards 15%
Progressed cards 20%
Add 6 progress to a card to a random card (shows which one) 25%
Progressed memories that cost closure instead 10%
