### ISSUE TITLE
Recurrence event glitch

### ISSUE THREAD

**Issue by 3CHosler** [db0/hypnagonia#208]
Choosing the recurrence event caused a soft crash; the screen is black and there is nothing to click. I experienced this twice, I believe at the same event.

**Comment by db0** [comment]
THanks. Is it possible to send me your logs? If you are playing in the browser, you need to open your browser console with F12. If on downloadable, you should have the logs in a secondary window.

**Comment by db0** [comment]
Ah nevermind, I can replicate it on my end. I'll fix
