### ISSUE TITLE
Game hung

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#239]
v0.36.0
I selected an upgrade for The Whippy-Flippy, the choice gained the yellow selection outline and then I clicked OK and the game stopped responding. No mouse or keyboard interaction is having any effect.

This is the second time I've had this with v0.36.0 but I'm afraid I can't remember what I was doing the first time; I don't think it was a card upgrade or any action that involved a pop-up. I don't recall ever having the game hang on me before 0.36.0.
[godot.log](https://github.com/db0/hypnagonia/files/8256029/godot.log)

**Comment by db0** [comment]
Oh damn. That's not good

**Comment by db0** [comment]
This happened again specifically with the whippy-flippy, or just with any upgrade in general?

**Comment by simply-peachy** [comment]
On the previous occasion I can't remember what I was doing. It may have been in an encounter. It was early in so unlikely related to the Whippy-Flippy, which I used extensively in a successful game previously.

**Comment by db0** [comment]
I think I managed to replicate it. Seems like an infinite loop

**Comment by simply-peachy** [comment]
Had a recurrence while upgrading Noisy Whip. It happened after clicking "OK", which gains its orange colouration before the game hangs.
[godot.log](https://github.com/db0/hypnagonia/files/8258247/godot.log)

**Comment by db0** [comment]
Yeah I've already tracked this. It's affecting cards with enhancements/scars only. Will be fixed in next version (if it ever passes CI)
