### ISSUE TITLE
"Masterwork Looking Glass" curio does not improve "Nothing to Fear"

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#242]
v.0.38.0
I had the "Absolutely Nothing to Fear" card, with an Intuition tag. I received the "Masterwork Looking Glass" curio and I think the Nothing to Fear was selected for upgrade, since it gained the green sun icon. It did not seem to improve in any way.
![Screenshot_20220316_124930](https://user-images.githubusercontent.com/51796618/158594148-161a282b-e4c7-4df1-9eee-e1726feacef9.png)

(The Confrontation in the screenshot was a card I had chosen to receive an Epic Upgrade; I presume it's increase from 8X to 11X was all from the Epic, and it was not selected by the Looking Glass)

**Comment by db0** [comment]
Nothing to fear cannot be selected by that artifact, because it doesn't do damage. What it got instead has is the Intuition tag, which makes you draw it first per ordeal (you can see it in the card info panels), but it must have received that from somewhere else.

**Comment by db0** [comment]
Maybe check your full deck. See if any other cards have been enhanced?
