### ISSUE TITLE
"Epic Upgrade"'d "Confrontation" card detrimental upgrade choice

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#243]
v0.38.0
I have a "Confrontation" card which has been Epic Upgraded to 11X. It's now received an upgrade through XP and the choices are both detrimental.
![Screenshot_20220316_125754](https://user-images.githubusercontent.com/51796618/158595243-40c80a66-d7d3-4b3e-80e6-a488c9ea956a.png)

**Comment by db0** [comment]
They're not. The upgrade window simply does not take upgrades into consideration. This will be fixed when I implement #204

**Comment by db0** [comment]
Also, how did you do the epic upgrade but still have 90 health?

**Comment by simply-peachy** [comment]
Max health has been going up and down a lot as I have the Dubious Painkillers and have chosen + and - through various NCEs, it was at 90 just by chance.
