### ISSUE TITLE
[CANCELLED] Substance addiction archetype

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#268]
### **Meet the archetype that needed serious reworks and had major flavoring problems. As well as moral issues! SUBSTANCE ADDICTION**
This archetype is an injustice archetype, for the master of synergists.
What will a substance abuser turn to when they're trapped in a nightmare realm?
This archetype is all about drawing the same type of cards with the same type of tags over and over again to get happy effect _with absolutely no overuse penalties whatsoever_! 

_Ultimately this is supposed to teach you addiction is bad, but also brings in a completely new playstyle to hypnagonia_
I tried to keep this simple for everyone, but let me know if we can flesh it out together

Card pool mechanics: addiction, hazy, courage, shaken, clarity, TBA

### The star mechanic(s): 
**Addiction**:  An umbrella term mechanic - Any colored addiction cards played adds 1 more  of their respective stack. If you have 0 of that colored addiction gain 2 stacks instead of 1.  Reduce stacks by 1 for each colored addiction at the end of the turn. 

Addiction = colored addiction, but colored addiction does not = addiction. 

**Colored addiction**: A card tag and effect representing the various effects that it will have on you. If the same type of colored addiction card is played more than once during your turn gain 1 stack of its respective addiction. 
   current - Red, Blue, and TBA 

**Hazy**: Dreamer/Torment has a 50% chance to miss an interpretation/Cause stress. Reduce stacks by 1 after missing or playing an interpretation card/causing anxiety. 

**Abstain**: Either forgets, releases, or scars a specified addiction card for an overall benefit. Can also remove or reduce addiction stacks as well. (You're better for doing this!)
   
###    **THE EFFECTS OF ADDICTION**
**Natural high**: Moderately positive buff that activates every time you gain a stack of addiction. (It's good for me right?)
**Crave**: Small negative debuff that applies everytime you don't play an addiction card. If your immersion is 0 at the start of the turn, you don't take crave effects.(combos well with apathy). (I NEED MORE!)
 **Overdoes**: When any addiction is = to 10 apply a moderate debuff and scar every addiction card with the same colored addicton. Be careful, future torments could take advantage of this whether you like it or not. 
**Withdrawal**: when an addiction reaches 0 receive a small but long-lasting debuff,  (I don't need it. I don't need it.)
  
**Red**: I'll never be smart or perceptive.
NH:Gain 1 clarity
C: deal 1 less damage and take 2 anxiety, 
W: Gain 3 stacks of confusion, take 5 anxiety

**Blue**: I'm weak without it.
NH: Gain 2 confidence at the beginning of each turn
C:  gain 2 stack of doubt
W: Gain 3 stacks of shaken, take 5 anxiety

**Green**: I've gotta rest somehow...
NH: relax for 3
C: take 2 anxiety
W:  gain 3 stacks of doubt, gain 3 stacks of envy

**Purple**:  I just don't have any energy in me.
NH: 50% chance to draw 1 more card at the beginning of each turn
C: 75% to discard a random card from your hand 
 W: you may not have more than 5 cards in your hand for 5 turns, take 3 anxiety

### **Let's Start!**

**Starter Curio**:  Just this once - At the beginning of the ordeal you are immune to addiction until you play an addiction car, will not stack with anything else. (Looks like hand holding a pill sillouhette)

**Starting card**:  Rose pill 

**Rose Pill**: 
Type: Action 
Flavor text: Maybe it'll clear my head.
Cost: 1
Effect: Interpret for 3, Gain 1  stack of temp. focus, gain 1 stack of red addiction. (Focus will stack with temp. focus)
rarity: Starter 
tags: Focus, Red addiction 
Progress upgrades: 
- cost 0, interpret for 6 gain 2 stacks of temp. focus, gain 2 stacks of red addiction
- cost 1, interpret for 3, gain 1 stack of focus, 50% chance to gain 1 stack of red addiction. (Playing the card might not add addiction)

**Violet concoction**: 
Type: Control
Flavor text: I feel like a better me!
Cost: 1
effect: gain 5 conf., gain 1 delayed courage, Gain blue addiction
rarity: common
tags: Courage, Blue addiction
progress upgrades: 
- cost 1 gain 10 confidence, gain 1 courage, Gain purple addiction
- cost 2 gain 2 stacks of untouchable, gain 2 delayed courage, Gain 2 stacks of blue addiction

**Viol splash**
Type: Action
Flavor: Take it! I don't want it!
Cost: 1
effect: interpret for 6, gain 1 stack of clarity, forget a violet concoction if you have one, forget.
rairty: common
tags: clarity, Abstain
note: work even if you have no violet concoctions within your deck
progress upgrades
- cost 3 interpret for 18, adjacent torments take 6 interpretation, every torment  affected receives 3 stacks of shaken, release a violet concoction if you have any, forget.
- cost 0 interpret for 24, adjacent torments take 8 interpretation, release this card, requires you to release a violet concotion to play.

**Sugar bursts**
type: concentration:
Flavor of text: Very sweet!
Cost: 1
effect: gain 1 more immersion every other turn, but gain 1 shaken every after that turn. (Happens inversely)
rarity; common
tags: shaken, immersion*
progress upgrades
- cost 2: gain 2 more immersion every turn, but gain 1 apathy and 1 shaken every other turn (1 turn is apathy, 1 turn is shaken) 
- cost 0: gain 1 more immersion every turn, gain 3 shaken

**Devour**
Type: Action
Flavor text: I can just eat away my problems. They don't taste very good though.
cost: 2
effect: Interpret for 10, relax for 1, if this overcomes a torment gain 3 max anxiety, and 3 shaken.
rarity: common
tags: relax, shaken
progress upgrades:
- cost 3 interpret for 20, relax for 3, if this overcomes a torment gain 3 max anxiety, gain 5 repressed lethargy. Forget
- cost 2 interpret for 1, if this does any interpretation to a torment, gain 3 max anxiety. 

**Half-life**
Type: Concentration
Flavor text: What have I become?
cost: 3
Effect: become immune to addiction for this ordeal, halve your remaining max Anxiety for this ordeal,
rairty: uncommon
tags: addiction, rationalization
note: the dreamer will not receive natural high effects either
progress upgrades:
- cost 0 become immune to addiction for this ordeal, reduce your max Anxiety by 3
- cost 3 become immune to debuffs for this ordeal, halve your remaining max Anxiety for this ordeal

**Uneeded toxicity**
Type: Action
Flavor text: It's not me, It's you!
cost: 1
Effect: take 5 anxiety, interpret for 12, apply 4 doubt and 1 confusion to the selected torment.
rarity: uncommon
tags: rationalization, doubt
progress upgrades:
- cost 2 gain 5 confidence interpret for 10 apply 5 stacks of doubt to the selected torment
-cost 3 take 3 anxiety, interpret for 6, apply 8 doubt and 3 shaken to the selected torment

**Smiley shrooms** 
Type: Control
Flavor text: Hey, Ima fun guy!
cost: 3
Effect: gain 8 confidence, gain 1 stack of courage, put this on the top of your draw pile and decrease its price by 1, gain 1 stack of blue addiction
rarity: uncommon
tags: addiction, courage
progress upgrades:
-cost 2 gain 12 confidence, gain 1 stack of courage, forget, add a copy of this card to your deck, gain 1 stack of blue addiction
- cost 0 gain 10 confidence, add 2 copies of this to your hand with release, 50% chance to gain 1 stack of of blue addiction. 
note: this card is meant to be a quick deck clogger.

**Burbly Brew**
Type: Action
Flavor text: i LiKe ThE wAy It BuBbLeS
cost: 2
Effect: interpret for 2 10 times, gain 1 stack of hazy, gain 1 stack of red addiction. forget
rarity: uncoomon
tags: addiction, hazy
progress upgrades:
- cost 1 interpret for 20, gain 1 stack of confusion. 
- cost 2 interpret for 1 20 times, gain 1 stack of red addiction, gain 1 more stack to interpret for 10 more. forget

**Liquid luck**
Type: Control
Flavor text: Testing your luck to see if it actually give you good luck
cost: 1
Effect: 50% chance to give 3 stacks of courage, 50% chance to give 3 stacks of doubt, 50% chance to gain a random stack of addiction.
raity: uncommon
tags: addiction, courage
- cost 1 if you have any debuffs 75% chance to remove all debuffs, 25% chance to double one of them. gain a random stack of addiction
- cost 0  50% chance to relax for 10 anxiety 50% chance to take 5 anxiety, 50% chance to gain 2 stacks of green addiction

TBA: Herbal manifest, The brakes*, Placebo, Guilty pleasure, Sobriety, Side-effects, Tetrohedric tonic*, Diet Diet, Splendid Stimulant, Sparking dust, Everglow Elixir*   

**Dreamless torpor ordeal wording change**: You felt yourself falling into a drunken stupor
- and you enjoyed every second of it. (same effect)
- You decided it would be best to abstain (no effect)

**Torment idea**: 
The seas are stormy tonight, clinging on to the edge of your ship, you hear the most loveliest sound
The "Two headed siren" - (focuses on applying an arsenal of alluring debuffs, until striking without warning)
Intent order is random. (Drown is never first though)
1: Questionable aria: Apply 1 stacks of 3 random addictions. (Will cause crave effects)
2: Beckon: Double the stacks of a current addiction. 
3:  Ring: Deal 1 stress 10 times. (Meant to get past untouchable)
4: Undying charm:  Apply 3 stacks of hazy
5: Drag down: Apply 5 stacks of shaken, deal 20 stress
6: Drown: If the dreamer has 6 or more stacks of an addiction, apply the overdose effect, and then apply clarity, if they don't have any stacks, stress for 40
Understanding: Lonely Mermaid: Deal a random overdoes effect to a random torment.

Perturbation suggestion: Dubious painkillers gives 2 stacks of a random addiction as well

**Comment by db0** [comment]
>Addiction: If the same type of colored addiction card is played more than once during your turn gain 1 stack of its respective addiction. Any colored addiction cards played afterwards continues adding 1 more stack. Reduce stacks by 1 each turn.

This means the addiction stack will go away automatically after the turn ends, as you will gain the stack, then the end-of-turn will remove a stack

**Comment by SkylarkHYP** [comment]
So maybe make it that it gives 2 stacks the first time you get it?

**Comment by db0** [comment]
I don't know. That's why I say you need to consider the mechanics carefully. I cannot design this for you as I don't know what you're thinking ;)
