### ISSUE TITLE
Perturbation "Lethe" seems to break memories

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#275]
v0.46.0
Lethe triggered during an ordeal, which reduces a random Memory's charge. During the next ordeal the Memory "The Poison Ivy Incident" gained its rainbow border to show it was ready, but clicking did nothing. Checking my Pathos showed I had only 3 Released Loneliness, when I need 10 to activate the memory.
[godot.log](https://github.com/db0/hypnagonia/files/8422753/godot.log)
![Screenshot_20220406_020107](https://user-images.githubusercontent.com/51796618/161875347-3f7b607f-0b53-4309-8820-3d2723ec1fa4.png)
![Screenshot_20220406_020114](https://user-images.githubusercontent.com/51796618/161875349-2699ff6b-1c88-4f78-9243-51d657d39235.png)

**Comment by db0** [comment]
That's not actually how memories work. They don't use your existing released pathos. Instead they slowly consume it while charging. When you use them, they do not burn any released pathos.

I'll see if the memory is broken by itself.

**Comment by db0** [comment]
Are you sure you didn't have Lethe in the hand when you clicked the memory?

**Comment by simply-peachy** [comment]
The one time I didn't take a full-screen screenshot. I'm not sure - I'll add it to the list of things to test.

**Comment by db0** [comment]
OK I'm closing this then. If this pops up again we can reopen
