### ISSUE TITLE
Add Recurrence understanding

### ISSUE THREAD

**Issue by db0** [db0/hypnagonia#288]
- It should copy Torment intents as an effect (somehow)
- It can only be upgraded by overcoming the Recurrence again. it can be upgraded 2 times.

**Comment by SkylarkHYP** [comment]
YES! Many thanks!
Also it would make people avoid recurrence less, since the AI thing is a little off-putting
I Like the personal balance you added!

I would use the same code for cards like the whippy flippy, but I don't know how you cooked this pasta, so I can't be 100% sure!
