### ISSUE TITLE
Game stuck during "Impassable Forest" NCE

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#292]
v0.48.0
During the "Impassable Forest" NCE I chose the "Shout for help" option. The card picker opened and I chose an L2 Confidence. The picker closed and the NCE failed to progress. All of the UI elements are working and the music is still playing. Looking in my library, I see no other cards have been added.

![Screenshot_20220414_013926](https://user-images.githubusercontent.com/51796618/163291978-260a2004-be1d-47cb-9ea7-bd27d0344d6b.png)
[godot.log](https://github.com/db0/hypnagonia/files/8485423/godot.log)

**Comment by db0** [comment]
Hm, yep. Looks like a script error. It prevented the game from progressing. Sorry about that. I'll look into it.
