### ISSUE TITLE
Store in mind's select mechanic is broken

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#320]
Store in mind's selection mechanic prompt the player to select a card, but after pressing ok, it does not work, and gets stuck to the hand. Reloading does not help. I've repeated this several times now, so it is an actual bug!
[https://photos.app.goo.gl/acmsXjKtxivVWcz69](https://photos.app.goo.gl/acmsXjKtxivVWcz69)

**Comment by db0** [comment]
Problem is that I cannot replicate it. I feel something is breaking on your end and the script is crashing. We need to see your console. 

In Chrome, can you press Ctrl + Shift + I while playing the game? It should open the console to the right.

**Comment by SkylarkHYP** [comment]
Ok. I'll run a test run soon, and get back to you!
