### ISSUE TITLE
Font size too small in preview of certain cards

### ISSUE THREAD

**Issue by IceTyp** [db0/hypnagonia#35]
Certain cards have too small font size in the preview. Note that in the card library this is not the case.

Here are two examples:

![image](https://user-images.githubusercontent.com/90767623/140381323-27dd42cb-85ee-4985-901d-b7177e332d3a.png)

![image](https://user-images.githubusercontent.com/90767623/140382262-90245bd1-983b-4dbf-89a7-8a45c975e4d0.png)

**Comment by db0** [comment]
I'm aware. But fortunately I found time today to work on a fix for that
