### ISSUE TITLE
The Tax collector | Act II frustration torment

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#353]
- [ ] More likely to appear if you have >100 of any released pathos.

I remember the silhouette of a despicable being in a trenchcoat  chasing  me down an alley during that stormy night. I had reached a dead end, there was no more running, it was time to pay the taxes....
 
We need more grudge torments, since cards like whirlwind barely have any downsides, making the overall meta unbalanced.  And murmurs is getting lonely! :0

Base Comprehension: 150 
Would summon 1 or 2 bills every turn
- Pileup: All torments gain 1-3 grudge 
- Overdue: Gain grudge or contentment  = to all torments on screen
- A bit taxing: Deal 9 9 stress to the dreamer., summon an extra bill (minion torment) if possible
-  Cold and calculated: gain 3 grudge, deal 9 stress to the dreamer
-  Keep the difference: Add an alertness to the top of the discard pile, gain 3 contentment
Note: You can pick and choose the ones you do or do not like btw. I just put a lot for variation.

The tax collector would start with  the permanent effect "Pestering", which is defined as "Whenever this torment's comprehension is increased, gain 1-2-3 grudge "
- [ ] The tax collector would also have doubt resistance! >:0

DOUBLE REWORK TIME: Bills are a minion torment that focuses more on staying in the ordeal, while slowly burning away at the dreamers health. Even though bills are likely to buildup a small amount of grudge, the intents would be unreliable enough so bills can be easily dealt with, when the opportunity presents itself!
- [ ] Also, upon overcoming any bill. The tax collector receives 15 interpretation. Thus bypassing the grudge buildup.

Base Comprehension: 5-10
- Apply 9 stress to the dreamer, gain 10 confidence
-  Gain 1 solidity and 3 grudge
- Gain 9 9 9 confidence
-  Gain 20 confidence, 
- Give all bills 10 confidence

Understanding:
Cost: 1
Effect: Move 50% of any grudge or contentment from a torment to the dreamer
Tags: Fading, grudge, contentment
Progress: 0/20
Upgrade:
- The debt collector: Move all grudge/contentment 
- Persistent taxman: Shuffle this card into your draw pile

Moral of the story: PAY YOUR TAXES :D
REWORKED it! @db0 !!!!

**Comment by db0** [comment]
Those stats are act3, not 2 :D

**Comment by db0** [comment]
If the bills always have evanescent 1, then there is no point in the player ever attacking them, or giving them grudge

**Comment by db0** [comment]
You're adding way too much grudge to the main torment. Anything above a  consistent 5 starts being very tricky to handle, and the intents you have will consistently hit 10 or 20. grudge. This means every single interpretation would hit back for 20! 

This needs to be adjusted a bit to be doable.

Try to think of how the flow of the ordeal will go that the torment will hurt the player but still be winnable, and simply cause too much anxiety when they player is all into chain actions. 

Also the bill minions need redesign. As I said above, their evanescent doesn't make sense.

**Comment by SkylarkHYP** [comment]
Hmm. Yeah the main premise is to make the dreamer focus on the constant piling up bills, which would be a dependable way for the dreamer to indirectly interpret the tax collector. I forgot to add that overcoming bills dealt interpretation to the tax collector! The reason why I put evanescent 1, was because it would constantly reset the bills, as well as preventing overflow. But it seems as it is too weird mechanicwise. So I can just tweak some numbers, and that will fix it!
