### ISSUE TITLE
OP combo between "@ Change of Mind @" and Light Backpack when deck is empty

### ISSUE THREAD

**Issue by IceTyp** [db0/hypnagonia#36]
When having **no cards in the deck** and playing "@ Change of Mind @", the card immediately returns to the hand.
It seems that the "Shuffle this card into your deck" effect does not work properly when there are no cards in the deck.

Before playing:
![Screenshot from 2021-11-04 22-39-10](https://user-images.githubusercontent.com/90767623/140423897-f6f18b67-4f52-4d0d-bfe2-ad60ffb450e6.png)

After playing (enemy got 6 damage):
![Screenshot from 2021-11-04 22-42-04](https://user-images.githubusercontent.com/90767623/140424267-0beb609d-fc9d-4ad1-8c7c-c42137a8fc65.png)

**Comment by IceTyp** [comment]
I just continued the game. This time I have 4 cards in the deck and Change of Mind still returns to my hand after playing.
So I guess, "@ Change of Mind @" is broken.

**Comment by IceTyp** [comment]
After some further investigation, it seems that "@ Change of Mind @" draws a card when played.

**Comment by db0** [comment]
That is weird. This is working as expected on my end o.O

**Comment by IceTyp** [comment]
Sorry that I write here that many comments.
I have "Light Backpack". Every time the deck is shuffled I draw a card. So there is no bug.
But the interaction seems a bit over powered. So this is a balancing issue.

**Comment by db0** [comment]
Right. I was indeed looking into the artifacts you had because I expected such an interaction :) Indeed, that is an OP combo :) I'll address it and thanks!
