### ISSUE TITLE
Shop encounter should not appear if the player has no released pathos at all!

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#364]
I saw a friend becking me over... There was nothing to discuss >:(
![image](https://user-images.githubusercontent.com/102880390/175720617-ca33aa27-afe7-4e70-b7c0-906b3d212ad9.png)

**Comment by db0** [comment]
This can happen if you don't pay enough attention and do not keep some masteries leftover. It's part of the game
