### ISSUE TITLE
Difficulties to run the desktop version

### ISSUE THREAD

**Issue by IceTyp** [db0/hypnagonia#37]
I have difficulties to make the desktop version 0.14.0 run on Ubuntu 20.04.

I tried to run _Hypnagonia_Linux.x86_64_. A window with the Godot logo appeared. After about five minutes the game had still not finished loading so I stopped it. Is this normal? Maybe I should wait longer.

Then, I tried _Hypnagonia_Windows.exe_ with Wine and it worked without any problems. I could even finish a game.

**Comment by db0** [comment]
Truth is I haven't tested the Linux build on my own, but I can't imagine why it would behave like that. I'll see if I can replicate it.

**Comment by db0** [comment]
I made some improvements on the loading times. Did anything?

**Comment by IceTyp** [comment]
Tried now the 0.16.1 Linux version on the same system. Still the same behavior.
I don't think it has to do with the loading times. But I will try it in the next days on a different computer.

**Comment by db0** [comment]
Does this work better on your new PC?

**Comment by IceTyp** [comment]
Yeah, v0.17.2 works on my new computer. (Ubuntu 21.10) 
I also tried v0.14.0 which takes more time to load but this version also works.

I have still no clue why it does not work on the old computer. It could be the older Ubuntu 20.04 or simply the 5 year old hardware.

**Comment by db0** [comment]
Weird. I'm doing some more improvements on the loading speed and I'll try in a low-powered VM to see if I can replicate

**Comment by IceTyp** [comment]
Maybe I was not clear enough. The desktop version **works** on the new computer. (Ubuntu 21.10)
After about two seconds, the menu appears and I can play.

**Comment by db0** [comment]
I understood. It's just weird that it doesn't work on the old one. This is why I want to test on my end.
