### ISSUE TITLE
Sky Leviathan -- Elite torment idea

### ISSUE THREAD

**Issue by Silberfarben** [db0/hypnagonia#380]
A torment about the impossible size of the world and your minuscule life.

_A great shadow loomed above. It did not notice me, not because it was senseless, for it could feel all of the universe. It did not notice me, not because it was unintelligent, for it had an intellect larger than I could comprehend. It did not notice me, not because it was sightless, but because I am simply too small. It is coming for my house, my village, my whole world. No, it is not. my whole existence is far too small for the Sky Leviathan to set goals by it. With a mere tensing of a muscle, it can destroy the whole universe. Without even a thought, it puts all mundane struggles to shame. If it's too big for anything to stop... then why try?_

The fight itself is against three torments, in the middle there is the Sky leviathan itself, with a very large health pool. On either side of it, there are smaller torments: Immobility. The sky leviathan deals something like 40 damage every 3-5 turns. The immobilities cause you one apathy per turn each, resulting in two apathy every turn. They also deal minor damage, and minor defense. 
The idea is that you have to prioritize either dealing much damage to the Leviathan itself with extra immersion, or take out the immobilities before tackling the Leviathan. 

When overcoming the Sky Leviathan:

_While there was nothing I could do, I realized that up to that moment, I had already been living in the face of impossibility. The world is far too large and far too impossible to understand, or overcome. Nevertheless, we still try. Recognizing this impossibly large Leviathan was only a reflection of an uncaring world, I went back to living as all humans do, worrying and still trying to do the best with what little I have._

**Comment by db0** [comment]
What does the Leviathan do in between 40-damage turns though?

**Comment by Silberfarben** [comment]
Defend, or perhaps heal the immobilities

**Comment by Silberfarben** [comment]
![](https://cdn.discordapp.com/attachments/989268312036896818/996723051192397936/sweet_tooth_None_6d737e7e-3728-46ca-a005-88077982c159.png)
![](https://cdn.discordapp.com/attachments/895578456820183061/996716260605825094/Leviathan.png)

yeee

**Comment by SkylarkHYP** [comment]
40 damage sounds like an act 3 torment 😬 
Wonder how boss curios, nothing to fear, and the koaler would impact this 🤔
