### ISSUE TITLE
Lotustus } Act II Trypophobe Frustration torment

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#382]
The more you look at the, the more unease washes over you. A tribute to trypophobia

_I remember my legs submerged in the murky water. I dredged through the endless swamp as my worry began to grow...
I was too late.. They has found me... Their thousands of mouths filled my ears with an evil laughter as I was surrounded by the endless pits of agitation. They had closed in on me, as I began to feel a painful and welling irritation across my skin..._

Lotustus would be a single torment with around like 130 comprehension. Every time the Lotustus would take interpretation, it would deal 1 anxiety back. In addition, Lotustus's intents adds focus to the dreamer but would copies the same exact amount next turn. The main premise of Lotustus would be to punish multi-attack decks, whilst not upsetting the power balance through grudge. Though Lotustus's main mechanics are small amounts of doubt, unease, and grudge.

Base comprehesnion: 130 (unlucky...)
Starting effects: 
Better unseen: Every time this torment takes int. the dreamer gains 1 anxiety
Look closer: Every turn, If the dreamer has any focus copy the exact amount next turn

Intent pool: (pick and choose)
A million shrieks: deal 1 1 1 1 1 stress, 
Eyesore: give the dreamer 1 stack of focus, add 1 unease to their draw pile
hideosity: Give the dreamer 1 focus, Apply 3 doubt to the dreamer
Oozing: Put an unease into the dreamer's discard pile, and gain 3 grudge, gain 8 perplexity
Look away: Gain 13 perplexity, gain 2 grudge, gain 1 solidity
Bleeding pores: give the dreamer 1 focus, apply 5 doubt, gain 5 perplexity
Agitation: Give the dreamer 1 focus, deal 30 stress
Hives: Apply 8 doubt to the dreamer, remove 8 grudge
Trypo trauma: Put 3 unease(s) into the dreamer's forget pile

Lotustus ordeal and journal art
![image](https://user-images.githubusercontent.com/102880390/179341109-c0fc8539-d5e4-483e-956a-a4810a9c43d9.png)
Image by SkylarkGSH via photoshop

Upon overcoming

_Even though I could feel and see the irritating blood red pores across my skin, I had to reassure myself that it couldn't hurt me physically. I denied my primal subconcious assumptions within me, and stormed away from the hideous amalgamations before me, and continued my trek through the bog. It was all too real for me, but I know I can get through it, and eventually get over it. Maybe I might just have to get used to it!_

Lotustus understanding
 cost: 1
Effect: Gain 7 grudge, add a temporary unease to your discard pile
 Progr. req.: X/13
Prog.
Blossomed Lotustus: gain 1 focus, gain 5 grudge, add temp. unease to discard
Withered Lotustus: Gain 8 grudge, gain 3 doubt
Lotus flower: Gain 1 inscrutable, gain 1 grudge, gain 1 focus

 Lotustus card art
![image](https://user-images.githubusercontent.com/102880390/179341220-396959e3-1ac8-4429-a902-aae714e4163c.png)
Image by SkylarkGSH via artbreeder.com and photoshop

**Comment by db0** [comment]
Why is it giving Focus to the dreamer?
