### ISSUE TITLE
Bug: Exhaustion doesn't forget out of reach on web build 

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#389]
![image](https://user-images.githubusercontent.com/102880390/180916510-89a39ad3-6c05-4f46-bd4e-f076670f9205.png)
![image](https://user-images.githubusercontent.com/102880390/180917109-259ef30f-7f3e-4ce7-bf70-b5e561273669.png)
works for confidence and others etc.
![image](https://user-images.githubusercontent.com/102880390/180919025-6148838a-3fb9-42db-a816-98254ca278e9.png)

**Comment by db0** [comment]
This is not a bug. You have a new artifact. Make sure it's not what is causing this. ;)
