### ISSUE TITLE
Goal: Repeating same torments in the same act is stale, and ruins flavor. 

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#394]
In my opinion repeating torments isn't very fun. But there's not much we can do atm. What I would recommend is that you make the torment stronger or even slightly different every time you "overcome" it. But this does hurt the idea of overcoming nightmares, since every torment is not recurrence. 

Anyways, to solve this in the future, we've just gotta intuitively brain dump more torment ideas here!

- [ ] Can't wait until this goal is reached

**Comment by db0** [comment]
Yes, pretty much. With about 10 torments and 3 elites per act this is mostly avoided. But more would be good.
