### ISSUE TITLE
Circular arguments needs 4 pieces of individual art

### ISSUE THREAD

**Issue by SkylarkHYP** [db0/hypnagonia#399]
![image](https://user-images.githubusercontent.com/102880390/180933378-a6beae22-08be-48f3-b732-625255cef95b.png)
![image](https://user-images.githubusercontent.com/102880390/180933407-c40335df-34b0-4c1d-8398-51dd7eefe3c8.png)
![image](https://user-images.githubusercontent.com/102880390/180933428-a2611df9-e3b3-4fde-9d04-84f2ae454779.png)
![image](https://user-images.githubusercontent.com/102880390/180933454-42d8e2fb-e693-44db-9f09-27bd425a05bc.png)
Character art by SkylarkGSH via sketchpad.io, adobe illustrator, photoshop, photomosh.com, and artbreeder.com

**Comment by db0** [comment]
As I explained, I have something better in mind for these.
