### ISSUE TITLE
Ideas for a pot plant encounter

### ISSUE THREAD

**Issue by IceTyp** [db0/hypnagonia#44]
## Pot plant encounter

In your wildest dreams, objects in your room turn into scary manifestations.
So does the pot plant near your window.

The pot plant could be based on a spider plant which is a tough and adaptable plant. Hence, it might turn into a tough torment.
If you gain control of this encounter (you defeat the torment), you are rewarded by the oxygen produced by your plant (artifact).

### Possible story text:

"Did I forget to water my spider plant?"
- "No, I did it yesterday for sure." (no battle)
- "I don't have a spider plant. I hate plants..." (no battle)
- "Last time might have been a week ago..." (battle against pot plant torment)

When torment is defeated:

"I remember now. Spider plants are durable. They do not need to be watered that often."
Gain pot plant artifact.

### Pot plant torment:

Can hit many times. (for each leaf)
If the battle takes long, new leaves grow and the plant can hit more often.
The torment might even produce child spider plants.
I don't think "healing" fits here thematically.

### Pot plant artifact:

Reduces your anxiety by providing fresh oxygen during the night. (healing)
A different effect might fit better.

**Comment by db0** [comment]
Great idea. Sounds like a good idea for an NCE-combat with a unique reward. Thanks

**Comment by db0** [comment]
Potted Plant NCE added without combat. I'll add use the combat idea elsewhere
