### ISSUE TITLE
Font size of some cards is off

### ISSUE THREAD

**Issue by IceTyp** [db0/hypnagonia#59]
The font size on some cards is too small. Note that the font size on the popup when hovering over the cards has the right size.
Interestingly, this seems to only occur in **full screen**.

![image](https://user-images.githubusercontent.com/90767623/142257581-5339f5b0-c9fd-4ea3-99da-f8c045b14181.png)

v0.17.0 on Firefox (Ubuntu 21.10)

**Comment by db0** [comment]
Hm, this might happen if something goes wrong when loading the card the first time. Maybe slow PC or something. Font sizes are recalculated when it detects a new version. Can you try again as I published a new version yesterday?

**Comment by MarcusAichmayr** [comment]
Actually, I have a new computer now.
I tried the new version (v0.17.1) and observed some recalculation when changing to full screen.

As you see in the picture, the fonts size looks better now:
![image](https://user-images.githubusercontent.com/70106364/142379013-9d4dc2dc-666d-4bcc-b154-7cab4a4e4898.png)

But now the cards overlap a bit. Is this intended? Also there is some free space on the right.
(resolution on this computer: 1920x1080)

**Comment by IceTyp** [comment]
Actually, I have a new computer now.
I tried the new version (v0.17.1) and observed some recalculation when changing to full screen.

As you see in the picture, the fonts size looks better now:
![image](https://user-images.githubusercontent.com/90767623/142379999-f63048d3-5683-4849-8d4b-20871697d7b3.png)
But now the cards overlap a bit. Is this intended? Also there is some free space on the right.
(resolution on this computer: 1920x1080)

**Comment by db0** [comment]
Not quite. This is a result of the game resizing the cards on the fly to fit you changing the resolution. I have simply not added code for the card library to adjust the grid size when this happens :)
