### ISSUE TITLE
Polygonal art for archetypes/journal?

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [db0/hypnagonia#6]
Forgive me if you're tired of hearing it from me due to the current workflow and issues of polygons.

Here's 2 examples, 1 semi-traced (flyer) and 1 rough/quick example (fearless). FXAA applied:

![archetypes_polygon_examples](https://user-images.githubusercontent.com/4397725/126022785-1a8f395c-f54a-4af3-93dd-076236771e83.png)

I'm sure nice+really stylized art could be made with this (particularly given the better circumstances than with enemies or cards), though again I'm not an artist thus not the best person to do that. The fearless example was originally going to be someone climbing a mountain but it didn't start out great.

**Comment by db0** [comment]
I think at this point you're basically making vector art with Godot, and I think this is a bit overkill. There's just dedicated programs to do this one can use.

**Comment by insomniacUNDERSCORElemon** [comment]
Aside from not using it, personally I find Inkscape to be very cluttered, and for a polygonal style Godot is MUCH easier/faster (right-click to delete points for a good example). Inkscape doesn't seem great for a polygonal style either, particularly because when you delete points it instead turns that edge into a curve.

If I wanted full vector art I'd probably try to learn Inkscape or something similar, but I wouldn't be interested in that unless Godot has native SVG rendering rather than some form of rasterization or mesh interpretation. Because I want it as designed and it's usually not hard to see when something is imperfectly recreated and even more so if it's not as scalable as native rendering would be.

Also I get wanting detail (that said, my examples are not the best with style *or* detail), but I feel like *that* is overkill for something people don't have much reason to look at for more than 3 seconds (and not even that when quick-start is used, at least now). At least it seems like a very far down-the-road thing where it'd actually be a valid concern for something like this.

Although if you're just trying to say that raster art will be a focus in the future, that's understandable. But I hope small download size stays a thing with this (and not a 200-500MB+ download).

**Comment by db0** [comment]
I am actually a big concerned as well about the size of the raster art when imported in Godot. It seems the game has reached 100MB, mostly because of the backgrounds I've added, even though the total size of the backgrounds in jpg is 8MB.
