### ISSUE TITLE
Crash selecting curio

### ISSUE THREAD

**Issue by simply-peachy** [db0/hypnagonia#92]
Running the Linux binary on Kubuntu 20.04. Not sure what version of the game as I couldn't find reference to the version/build number anywhere, but I downloaded it from ~~here~~ itch.io on the 24th December so I'm assuming 0.21.0.

I was awarded a curio after winning an encounter. I clicked on it and the game immediately crashed to desktop. The curio was called "artifact_name" but I'm afraid I can't remember what it did. I guess there may be a typo in ArtifactDefinitions.gd to leak the "artifact_name" string into the game; I had a look but couldn't see any glaring ones.

[godot.log](https://github.com/db0/hypnagonia/files/7776613/godot.log)

Loving the game!

**Comment by simply-peachy** [comment]
Possibly relevant: had another "{artifact_name}" curio turn up, but selecting it did not crash the game. It had the effect "The first time you reshuffle your deck, deal damage to all enemies equal to your discard pile".

**Comment by db0** [comment]
Cheers I'll take a look

**Comment by db0** [comment]
PS, the version is always visible on the top right, and on the starting screen on the bottom right
